# Generated by Django 6.0.1 on 2026-01-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_following_delete_artist_delete_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='artist_id',
            field=models.IntegerField(),
        ),
    ]
